### PR TITLE
Added method useStateAndAsyncStorage for React Native

### PR DESCRIPTION
**Pull request by rommyarb**
Added method `useStateAndAsyncStorage` to support react-native's **AsyncStorage**

### CODE REVIEW

**Comment by harrysolovay** [comment]
@rommyarb thank you for the contribution!

**Comment by joeyparis** [comment]
This breaks support for programs not using `react-native`. We can probably wrap `useStateAndAsyncStorage` with a `try/catch` and log a console error that this method is only available for programs using React Native. What are your thoughts?

**Comment by harrysolovay** [comment]
@joeyparis that should solve the problem. Realizing now though...––in this PR––there's no line that imports `AsyncStorage`. I'm surprised that this is working in React Native, as I'm pretty sure `AsyncStorage` is NOT a global. Perhaps a better solution would be to enable users to pass in their storage methods. Although honestly I'm tempted to just revert this commit and call it a day. What were you thinking would be the best route forward?

**Comment by joeyparis** [comment]
@harrysolovay It looks like they use `require` on line 100 to bring in `AsnycStorage`. It also looks like this method of storage is deprecated on `react-native` (https://facebook.github.io/react-native/docs/asyncstorage). Personally, I have no issue reverting this commit and calling it a day I just wouldn't want to break anyone else's program that might be relying on this. So I guess for that reason, and that reason only, adding a `try/catch` might be worth it but since it's deprecated just reverting the commit probably might be worth it.

I do like the idea of allowing users to pass their own storage messages, but that's definitely a project for another day haha

**Comment by harrysolovay** [comment]
@joeyparis I'm grateful for the attention you're paying to this package. I can tell you're more invested in this repo than I am. I'd like to transfer it to your ownership, and add you as an admin on NPM. Would you feel comfortable with that, and you can take this package in the direction you see fit?

**Comment by joeyparis** [comment]
@harrysolovay Certainly! Just let me know whatever information you need from me, I'm happy to help :)

**Comment by harrysolovay** [comment]
@joeyparis please delete your fork of `persistence-hooks`, otherwise, I can't transfer ownership. Also, what's your NPM username?

**Comment by joeyparis** [comment]
@harrysolovay Done! My npm username is the same as my Github: @joeyparis

**Pull request merged**
